FROM chjdev/fanlens:root-v4

COPY config/gunicorn.py /etc/gunicorn/
COPY common /usr/src/common
COPY web/setup.py /usr/src/web/
COPY web/ui /usr/src/web/ui
COPY web/flask_modules /usr/src/web/flask_modules

RUN pip install -e /usr/src/common && \
    pip install -e /usr/src/web && \
    pip install gunicorn

USER app
EXPOSE 5000
