FROM chjdev/fanlens:root-v4

COPY base /usr/src/base
COPY web /usr/src/web
COPY docker/web/requirements.txt /usr/src/deploy/web/requirements.txt
COPY docker/web/config.py /etc/gunicorn/

RUN pip install -e /usr/src/base && \
    pip install -e /usr/src/web && \
    pip install -r /usr/src/deploy/web/requirements.txt

EXPOSE 5000
